name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: make -C ${{github.workspace}}/build -j

    - name: Test
      run: cmake --build ${{github.workspace}}/build --target test -j
